"""initial schema

Revision ID: 0224f91af360
Revises: 
Create Date: 2025-10-04 12:26:37.765669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0224f91af360'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=True)
    op.create_index(op.f('ix_achievements_metric'), 'achievements', ['metric'], unique=False)
    op.create_table('bounty_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounty_templates_code'), 'bounty_templates', ['code'], unique=True)
    op.create_table('graph_quest_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(), nullable=False),
    sa.Column('choice_text', sa.String(), nullable=True),
    sa.Column('condition_data', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_quest_connections_from_node_id'), 'graph_quest_connections', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_graph_quest_connections_to_node_id'), 'graph_quest_connections', ['to_node_id'], unique=False)
    op.create_table('graph_quest_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('node_data', sa.String(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('is_start', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_quest_nodes_quest_id'), 'graph_quest_nodes', ['quest_id'], unique=False)
    op.create_table('graph_quest_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('current_node_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('visited_nodes', sa.String(), nullable=True),
    sa.Column('quest_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest_id', name='uq_graph_user_quest')
    )
    op.create_index(op.f('ix_graph_quest_progress_quest_id'), 'graph_quest_progress', ['quest_id'], unique=False)
    op.create_index(op.f('ix_graph_quest_progress_user_id'), 'graph_quest_progress', ['user_id'], unique=False)
    op.create_table('hero_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('str_bonus', sa.Integer(), nullable=False),
    sa.Column('agi_bonus', sa.Integer(), nullable=False),
    sa.Column('int_bonus', sa.Integer(), nullable=False),
    sa.Column('vit_bonus', sa.Integer(), nullable=False),
    sa.Column('luk_bonus', sa.Integer(), nullable=False),
    sa.Column('stat_growth', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hero_class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('base_str', sa.Integer(), nullable=False),
    sa.Column('base_agi', sa.Integer(), nullable=False),
    sa.Column('base_int', sa.Integer(), nullable=False),
    sa.Column('base_vit', sa.Integer(), nullable=False),
    sa.Column('base_luk', sa.Integer(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('attribute_points', sa.Integer(), nullable=False),
    sa.Column('talent_points', sa.Integer(), nullable=False),
    sa.Column('talents', sa.String(), nullable=False),
    sa.Column('daily_progress', sa.String(), nullable=False),
    sa.Column('weekly_progress', sa.String(), nullable=False),
    sa.Column('daily_reset_at', sa.String(), nullable=True),
    sa.Column('weekly_reset_at', sa.String(), nullable=True),
    sa.Column('world_flags', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('last_activity_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_hero')
    )
    op.create_index(op.f('ix_heroes_hero_class_id'), 'heroes', ['hero_class_id'], unique=False)
    op.create_index(op.f('ix_heroes_user_id'), 'heroes', ['user_id'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('effect_data', sa.String(), nullable=False),
    sa.Column('can_use_in_combat', sa.Boolean(), nullable=False),
    sa.Column('can_use_outside_combat', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_code'), 'items', ['code'], unique=True)
    op.create_table('monster_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('base_str', sa.Integer(), nullable=False),
    sa.Column('base_agi', sa.Integer(), nullable=False),
    sa.Column('base_int', sa.Integer(), nullable=False),
    sa.Column('base_vit', sa.Integer(), nullable=False),
    sa.Column('base_luk', sa.Integer(), nullable=False),
    sa.Column('stat_growth', sa.String(), nullable=False),
    sa.Column('monster_type', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('last_activity_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monsters_monster_class_id'), 'monsters', ['monster_class_id'], unique=False)
    op.create_table('quest_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('next_node_id', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_nodes_quest_id'), 'quest_nodes', ['quest_id'], unique=False)
    op.create_table('quest_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('current_node_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest_id', name='uq_user_quest')
    )
    op.create_index(op.f('ix_quest_progress_quest_id'), 'quest_progress', ['quest_id'], unique=False)
    op.create_index(op.f('ix_quest_progress_user_id'), 'quest_progress', ['user_id'], unique=False)
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('town_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(), nullable=False),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_town_connections_from_node_id'), 'town_connections', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_town_connections_to_node_id'), 'town_connections', ['to_node_id'], unique=False)
    op.create_table('town_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('town_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('node_data', sa.String(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_town_nodes_town_id'), 'town_nodes', ['town_id'], unique=False)
    op.create_table('towns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('town_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_town_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('town_id', sa.Integer(), nullable=False),
    sa.Column('current_node_id', sa.Integer(), nullable=False),
    sa.Column('visited_nodes', sa.String(), nullable=True),
    sa.Column('town_data', sa.String(), nullable=True),
    sa.Column('first_visited_at', sa.String(), nullable=False),
    sa.Column('last_visited_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'town_id', name='uq_user_town')
    )
    op.create_index(op.f('ix_user_town_progress_town_id'), 'user_town_progress', ['town_id'], unique=False)
    op.create_index(op.f('ix_user_town_progress_user_id'), 'user_town_progress', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('active_bounties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('available_from', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['bounty_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_bounties_template_id'), 'active_bounties', ['template_id'], unique=False)
    op.create_table('hero_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.String(), nullable=True),
    sa.Column('progress_updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hero_id', 'achievement_id', name='uq_hero_achievement')
    )
    op.create_index(op.f('ix_hero_achievements_achievement_id'), 'hero_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_hero_achievements_hero_id'), 'hero_achievements', ['hero_id'], unique=False)
    op.create_table('hero_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hero_id', 'item_id', name='uq_hero_item')
    )
    op.create_index(op.f('ix_hero_inventory_hero_id'), 'hero_inventory', ['hero_id'], unique=False)
    op.create_index(op.f('ix_hero_inventory_item_id'), 'hero_inventory', ['item_id'], unique=False)
    op.create_table('hero_reputation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('faction_code', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hero_id', 'faction_code', name='uq_hero_faction')
    )
    op.create_index(op.f('ix_hero_reputation_hero_id'), 'hero_reputation', ['hero_id'], unique=False)
    op.create_table('quest_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_requirements_quest_id'), 'quest_requirements', ['quest_id'], unique=True)
    op.create_table('hero_bounty_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('active_bounty_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_data', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['active_bounty_id'], ['active_bounties.id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hero_id', 'active_bounty_id', name='uq_hero_bounty')
    )
    op.create_index(op.f('ix_hero_bounty_progress_active_bounty_id'), 'hero_bounty_progress', ['active_bounty_id'], unique=False)
    op.create_index(op.f('ix_hero_bounty_progress_hero_id'), 'hero_bounty_progress', ['hero_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hero_bounty_progress_hero_id'), table_name='hero_bounty_progress')
    op.drop_index(op.f('ix_hero_bounty_progress_active_bounty_id'), table_name='hero_bounty_progress')
    op.drop_table('hero_bounty_progress')
    op.drop_index(op.f('ix_quest_requirements_quest_id'), table_name='quest_requirements')
    op.drop_table('quest_requirements')
    op.drop_index(op.f('ix_hero_reputation_hero_id'), table_name='hero_reputation')
    op.drop_table('hero_reputation')
    op.drop_index(op.f('ix_hero_inventory_item_id'), table_name='hero_inventory')
    op.drop_index(op.f('ix_hero_inventory_hero_id'), table_name='hero_inventory')
    op.drop_table('hero_inventory')
    op.drop_index(op.f('ix_hero_achievements_hero_id'), table_name='hero_achievements')
    op.drop_index(op.f('ix_hero_achievements_achievement_id'), table_name='hero_achievements')
    op.drop_table('hero_achievements')
    op.drop_index(op.f('ix_active_bounties_template_id'), table_name='active_bounties')
    op.drop_table('active_bounties')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_town_progress_user_id'), table_name='user_town_progress')
    op.drop_index(op.f('ix_user_town_progress_town_id'), table_name='user_town_progress')
    op.drop_table('user_town_progress')
    op.drop_table('towns')
    op.drop_index(op.f('ix_town_nodes_town_id'), table_name='town_nodes')
    op.drop_table('town_nodes')
    op.drop_index(op.f('ix_town_connections_to_node_id'), table_name='town_connections')
    op.drop_index(op.f('ix_town_connections_from_node_id'), table_name='town_connections')
    op.drop_table('town_connections')
    op.drop_table('quests')
    op.drop_index(op.f('ix_quest_progress_user_id'), table_name='quest_progress')
    op.drop_index(op.f('ix_quest_progress_quest_id'), table_name='quest_progress')
    op.drop_table('quest_progress')
    op.drop_index(op.f('ix_quest_nodes_quest_id'), table_name='quest_nodes')
    op.drop_table('quest_nodes')
    op.drop_index(op.f('ix_monsters_monster_class_id'), table_name='monsters')
    op.drop_table('monsters')
    op.drop_table('monster_classes')
    op.drop_index(op.f('ix_items_code'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_heroes_user_id'), table_name='heroes')
    op.drop_index(op.f('ix_heroes_hero_class_id'), table_name='heroes')
    op.drop_table('heroes')
    op.drop_table('hero_classes')
    op.drop_index(op.f('ix_graph_quest_progress_user_id'), table_name='graph_quest_progress')
    op.drop_index(op.f('ix_graph_quest_progress_quest_id'), table_name='graph_quest_progress')
    op.drop_table('graph_quest_progress')
    op.drop_index(op.f('ix_graph_quest_nodes_quest_id'), table_name='graph_quest_nodes')
    op.drop_table('graph_quest_nodes')
    op.drop_index(op.f('ix_graph_quest_connections_to_node_id'), table_name='graph_quest_connections')
    op.drop_index(op.f('ix_graph_quest_connections_from_node_id'), table_name='graph_quest_connections')
    op.drop_table('graph_quest_connections')
    op.drop_index(op.f('ix_bounty_templates_code'), table_name='bounty_templates')
    op.drop_table('bounty_templates')
    op.drop_index(op.f('ix_achievements_metric'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
